name: Market Analysis Bot BTC and Gold

on:
  schedule:
      - cron: '15 */4 * * *'
  workflow_dispatch:

jobs:
  market-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Market Analysis
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python analysis/market_bot.py
